follow html guidelines
PUP-BSIT/exercise-12-vrzn_webdev pull request #13
Opened 2023-11-06 07:35 UTC by go-christianharrel

@JheanKhendrick I have made the necessary adjustments to my code in response to the raised issue and your valuable suggestions. I kindly request a review of these changes. Your feedback is greatly appreciated. **Thank you!**

2023-11-06 08:03 UTC, JheanKhendrick requested changes
I failed to include that you have a container2 class on your HTML please change this as well. 

I apologize for the trouble and I hope you understand

Thank You!

2023-11-06 08:10 UTC, JheanKhendrick requested changes

2023-11-06 08:10 UTC, JheanKhendrick commented on go_christianharrel/go_christianharrel.html
>      <section class="container container2">
```suggestion
    <section class="container container-two">
```

2023-11-06 08:13 UTC, JheanKhendrick approved these changes

2023-11-06 08:13 UTC, go-christianharrel commented on go_christianharrel/go_christianharrel.html
>      <section class="container container2">
I'm having a problem pushing my changes

2023-11-06 08:36 UTC, JheanKhendrick commented on go_christianharrel/go_christianharrel.html
>      <section class="container container2">
me too

2023-11-07 08:26 UTC, go-christianharrel commented on go_christianharrel/go_christianharrel.html
>      <section class="container container2">
I can finally push my commit now ^^

2023-11-07 08:27 UTC, Galope-Jhean approved these changes
LGTM!

2023-11-07 08:34 UTC, merged